#+HUGO_BASE_DIR: c:/Users/leona/Desktop/programacao/blog/
#+HUGO_SECTION: posts

#+TITLE: decepções básicas
#+AUTHOR: santi
#+HUGO_CUSTOM_FRONT_MATTER: :subtitle "se 77 + 33 fosse 100..."
#+HUGO_WEIGHT: auto
#+HUGO_TAGS: matematica bases-numericas
#+HUGO_AUTO_SET_LASTMOD: t

#+HUGO_CUSTOM_FRONT_MATTER: :katex true

#+HUGO_DRAFT: false

* tristezas e mais tristezas
ah! que belo o mundo seria se

$$ 77 + 33 = 100$$

mas infelizmente não é o que acontece. vivemos num mundo falho e imperfeito, a vida é arbitrária e sem sentido, não há motivo para sequer procurar estender nossa estada aqui, tudo é fútil e inócuo e devemos todos cometer suicídio.

ou será que não acontece?

bases numéricas são um assunto extremamente arbitrário: na maior parte do tempo usamos bases decimais, mas inconscientemente utilizamos outras bases em outros contextos, seja para o tempo (já reparou como 0.5 horas são 30 minutos?), seja para contar ovos (de 12 em 12) ou mesmo na linguagem mística dos computadores: binário.

fato é que, para toda base numérica $x$, podemos calcular o valor de seus digitos com a formula geral:

$$ valor = a_k x^{k} + a_{k-1} x^{k-1} + ... + a_2 x^{2} + a_1 x^{1} + a_0 x^{0} $$

ou, simplificando

$$ valor = \sum_{i=0}^{k} a_i x^{i} $$

para o caso decepcionante supracitado, podemos dissecá-lo como

$$ 7 \cdot 10^{1} +  7 \cdot 10^{0} + 3 \cdot 10^{1} + 3 \cdot 10^{0} =  1 \cdot 10^{3} $$

e, interessantemente re-agrupá-lo como

$$ 7 (10^{1} + 10^{0}) + 3 (10^{1} + 10^{0}) = 1 (10^{2})$$

curiosamente, ou não curiosamente, muitos alunos do /ótimo/ sistema de educação brasileiro já se encontraram de frente com a expressão entre parênteses: sim, é a soma de uma progressão geométrica. e para os que não lembram, podemos facilmente achar a fórmula fechada para tal com:

$$ S_{pg} = x^{k} + x^{k-1} + x^{k-2} + ... + x^{2} + x^{1} + x^{0} $$

$$ x \cdot S_{pg} = x^{k+1} + x^{k} + x^{k-1} + ... + x^{3} + x^{2} + x^{1} $$

$$ x \cdot S_{pg} - S_{pg} = x^{k+1} - x^{0} $$

$$ S_{pg} = \frac{x^{k+1} - x^{0}}{x - 1}$$

E vemos que, não surpreendentemente,

$$  \frac{10^{2} - 1}{10 - 1} = \frac{99}{9} = (10^1 + 10^0) = 11$$

> ok, entendi, matemática chata, e dai?

acalme-se jovem padawan, estamos apenas começando.

* subvertendo a realidade

> quando a verdade dói, ignore-a e crie a sua própria

provavelmente ninguém nunca disse isso. mas é verdade: quando os fatos não estão a seu favor, apenas os ignore. é simples assim. portanto, definemos aqui a base $b$ tal que

$$ 77_b + 33_b = 100_b $$

onde a notação $número_b$ indica que $número$ é calculado na base $b$. sabemos que, para nossa base ser válida, precisa satisfazer

$$ 7(b^{1} + b^{0}) + 3(b^{1} + b^{0}) = b^{2} $$

$$ (b^{1} + b^{0})(7 + 3) = b^{2} $$

e, portanto, pela fórmula da soma de pg,

$$ 10 \left( \frac{b^{2} -1}{b - 1} \right) = b^2 $$

resolvendo um pouco mais,

$$ 10b^2 - 10 = b^3 - b^2 $$

$$ b^3 - 11b^2 + 10 = 0$$

essa fórmula nos dá, então, três possíveis valores para $b$. um deles é trivial: $b=1$, visto que $1 + 11 - 10$ realmente /é igual/ a 0. entretanto, as outras duas soluções são muito mais interessantes: $b = 5 \pm \sqrt{35}$

e, ainda mais entusiasticamente, /apenas um/ desses valores é de fato positivo: $5 + \sqrt{35}$, e portanto sabemos que

$$ 77_{5 + \sqrt{35}} + 33_{5 + \sqrt{35}} = 100_{5 + \sqrt{35}}$$

*eureka!*

* generalizando...

por que parar com $77 + 33 = 100$? por quê não $777 + 333 = 1000$? ou $7777 + 3333 = 10000$? realmente, não precisamos parar nessas quantidades de dígitos arbitrários, podemos ir *além*. Portanto, seja $B(n)$ a base necessária para que

$$ 77...7_{B(n)} (n~digitos) + 33...3_{B(n)} (n~digitos) = 10....0_{B(n)}(n+1~digitos) $$ 

sabemos que a fórmula

$$ 7 (B(n)^{n} + ... + B(n)^1 +B(n)^0) + 3 (B(n)^{n} + ... +B(n)^1 +B(n)^0) =B(n)^{n+1}$$

deve ser satisfeita. portanto

$$ 10 \left( \frac{B(n)^{n+1} - 1}{B(n)- 1} \right) =B(n)^{n+1}$$

logo, organizando a equação, e usando a fórmula da soma de pg, achamos nossa fórmula geral para $B(n)$:

$$ B(n)^{n+2} - 11 B(n)^{n+1} + 10 = 0$$

*eureka!$^2$*

desse modo, para qualquer quantidade de dígitos $n$, podemos calcular, /dada suficiente quantidade de magia negra/, sua respectiva *base ideal*. por essa fórmula, podemos, por exemplo, achar a resposta para a $B(2)$:

$$ B(2) = \frac{1}{3} \left(10 + \sqrt[3]{1585 - 15 \sqrt{1401}} + \sqrt[3]{5 (317 + 3 \sqrt{1401})} \right)$$

para o caso $B(3)$, apesar de o wolfram alpha encontrar /de maneira mística/ a solução exata, não irei incluí-la pois é *enorme*

e não respondo para o caso de $B(4)$ em diante pois nem o wolframalpha foi capaz de empregar /magia negra/ suficiente para encontrar a solução exata, apesar de serem equações relativamente simples.

* adendos finais

alguns podem já ter notado que a base $b$ não funcionará /apenas/ para o caso $77_b + 33_b = 100_b$. de fato, quaisquer dois números que somem para 10 irão funcionar nessa equação, portanto $66_b + 44_b = 100_b$ ou $88_b + 22_b = 100_b$.

outro caso curioso é para $B(0)$: vemos que $B(0)^2 - 11 B(0) + 10 = 0$ tem duas soluções interessantes $B(0)_1 = 1$ e $B(0)_2 = 10$. enquanto ainda não sei direito como interpretar o caso onde 1 é o resultado, $B(0) = 10$ nos diz que

$$ 7 \cdot 10^0 + 3 \cdot 10^0 = 10^1 $$

ou, simplesmente,

$$ 7 + 3 = 10$$

além disso, deixei propositalmente escondido um fato bem importante: as equações possuirão graus cada vez maiores e eu não provei que $B(n)$ será sempre um número real (pois pode muito bem acontecer que todas as soluções de $B(n)$ sejam imaginárias, até então). pois bem, apesar de acreditar que tal fato seja verdadeiro, *eu não sei como provar isso*, e portanto deixo aqui a *conjectura de santi*:

$\forall n \in \mathbb{N}, n \geq 0$, $\exists! k \in \mathbb{R}, k > 0$ tal que

$$k^{n+2} - 11 k^{n+1} + 10 = 0 $$

onde $k$ é a /única/ solução real positiva para a fórmula geral de $B(n)$. apesar de não saber provar, realmente acredito que essa afirmação seja verdadeira.

e sim, eu também ainda não sei bem como definir /uma base não inteira/, mas isso fica como dever de casa para àqueles que acreditam que matemática deve sempre ser aplicável à vida real.


